"""add_shake_sessions_table

Revision ID: 7a9055a3f1fc
Revises: 5762b0b0b451
Create Date: 2025-12-12 11:49:06.161264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9055a3f1fc'
down_revision = '5762b0b0b451'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shake_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('latitude', sa.String(length=20), nullable=False),
    sa.Column('longitude', sa.String(length=20), nullable=False),
    sa.Column('accuracy_m', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('matched_user_id', sa.BigInteger(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'MATCHED', 'EXPIRED', name='shakesessionstatus'), nullable=False),
    sa.Column('meeting_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shake_sessions_created_at'), 'shake_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_shake_sessions_expires_at'), 'shake_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_shake_sessions_id'), 'shake_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_shake_sessions_matched_user_id'), 'shake_sessions', ['matched_user_id'], unique=False)
    op.create_index(op.f('ix_shake_sessions_meeting_id'), 'shake_sessions', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_shake_sessions_status'), 'shake_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_shake_sessions_user_id'), 'shake_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shake_sessions_user_id'), table_name='shake_sessions')
    op.drop_index(op.f('ix_shake_sessions_status'), table_name='shake_sessions')
    op.drop_index(op.f('ix_shake_sessions_meeting_id'), table_name='shake_sessions')
    op.drop_index(op.f('ix_shake_sessions_matched_user_id'), table_name='shake_sessions')
    op.drop_index(op.f('ix_shake_sessions_id'), table_name='shake_sessions')
    op.drop_index(op.f('ix_shake_sessions_expires_at'), table_name='shake_sessions')
    op.drop_index(op.f('ix_shake_sessions_created_at'), table_name='shake_sessions')
    op.drop_table('shake_sessions')
    # ### end Alembic commands ###

