"""Add status field to friendships

Revision ID: aab99b69ca25
Revises: 347832a0f1be
Create Date: 2025-11-27 00:16:29.212216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab99b69ca25'
down_revision = '347832a0f1be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendships', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('friendships', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_friendships_status'), 'friendships', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friendships_status'), table_name='friendships')
    op.drop_column('friendships', 'updated_at')
    op.drop_column('friendships', 'status')
    # ### end Alembic commands ###

